theme = "default"

[providers]
default = ["desktopapplications", "runner", "calc"]
empty = ["desktopapplications"]

[[providers.prefixes]]
prefix = "="
provider = "calc"               # Calculator

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
